### ISSUE TITLE
这个渲染器不支持{% raw %}语法吗，为啥没作用

### ISSUE THREAD

**Issue by chjiyun** [CHENXCHEN/hexo-renderer-markdown-it-plus#11]
```
{% raw %}
<img src="" title="" alt ="">
{% endraw %}
```
这样的语法hexo是支持的，但是img还是被a标签包裹了，不知作者有没有注意到这个问题

**Comment by CHENXCHEN** [comment]
`md` 解析器不支持这些语法。我是第一次获知还有这种语法，我没有在官网找到相关语法的资料。。请问可以给出关于这个语法的链接吗？这样便于测试

**Comment by hanai** [comment]
https://hexo.io/docs/tag-plugins.html#Raw

**Comment by CHENXCHEN** [comment]
我测试是兼容的。。
另：`html` 标签可以直接用，不前用那个语法
```
{% raw %}

{% endraw %}
```

**Comment by chjiyun** [comment]
@CHENXCHEN  我希望生成文件后是 img 不要被 a 标签 包裹， 有什么方法么
