### ISSUE TITLE
从默认的marked换到这个插件后遇到了几个问题

### ISSUE THREAD

**Issue by gapplef** [CHENXCHEN/hexo-renderer-markdown-it-plus#12]
从默认的marked换到这个插件后遇到了几个问题：

* 插入的图片路径或图片名中含有空格时，图片无法显示
```
![example](/path/to/example figure.jpg)
```

* 图片位于布局标签内，且插入图片的行与布局标行间之间没有空行，图片无法显示
```
<div style="text-align:center">
![example](/path/to/example.jpg)
</div>
```
* 加一个空行，图片就可以显示了
```
<div style="text-align:center">

![example](/path/to/example.jpg)
</div>
```

* 文字位于布局标签内时，换行无效
```
<div style="text-align :right;">
换行
测试
</div>
```
在使用默认的marked时不存在这几个问题。

**Comment by CHENXCHEN** [comment]
1. 图片中的路径如果有空格替换为`%20`(这是url的空格编码)
2. 这个问题应该是`markdown-it`的`bug`
3. 内容位于html标签之内，使用`<br>`来换行

**Comment by gapplef** [comment]
问题已经解决了，为了解决问题顺便把HTML/CSS入门了😂，不过还是感谢回复！
用`<br>`换行解决最后一个问题的话，使用默认的marked的时候又会多出一个空行，就很烦，暂时用`<pre>`标签解决

**Comment by zyzyz** [comment]
@CHENXCHEN  关于换行问题，在中文日文一句话后面加两个空格能够生成<br>标签，但是英文后面却无法生成，请问这是否为bug?
