### ISSUE TITLE
默认插件中加入任务列表支持

### ISSUE THREAD

**Issue by gapplef** [CHENXCHEN/hexo-renderer-markdown-it-plus#15]
markdown-it默认不支持任务列表
能否将[markdown-it-task-lists](https://github.com/revin/markdown-it-task-lists)也加入默认支持的插件
感觉这是一个比较基本的功能。

**Comment by CHENXCHEN** [comment]
第三方插件请参考 [文档](https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus#add-other-markdown-it-plugins)
