### ISSUE TITLE
Error: Cannot find module 'highlight.js'

### ISSUE THREAD

**Issue by zhangyu0806** [CHENXCHEN/hexo-renderer-markdown-it-plus#2]
Error: Cannot find module 'highlight.js'

http://odandsezm.bkt.clouddn.com/Hexo/_image/2017-10-12-10-44-49.jpg

**Comment by CHENXCHEN** [comment]
just install `highlight.js`, `npm install highlight.js --save`

**Comment by CHENXCHEN** [comment]
sorry, my mistake, I will add this package to `dependencies`

**Comment by CHENXCHEN** [comment]
version **1.0.2** fix it.

**Comment by zhangyu0806** [comment]
It works, thanks!
