### ISSUE TITLE
无法解析

### ISSUE THREAD

**Issue by hakale** [CHENXCHEN/hexo-renderer-markdown-it-plus#3]
对于数据
> 给定数据集 $D=\{(x_1, y_1) ,(x_2, y_2),\dots, (x_m, y_m)\}$ ,学

![](https://ws4.sinaimg.cn/large/006tKfTcgy1fkgkgqxpk5j30f10290st.jpg)
已经替换解析器为`hexo-renderer-markdown-it-plus`,修改配置文件,引入css
![](https://ws3.sinaimg.cn/large/006tKfTcly1fkgkkwhl9gj30db06vwev.jpg)

![](https://ws3.sinaimg.cn/large/006tKfTcly1fkgkjoe9s4j30jf04v3yx.jpg)

**Comment by CHENXCHEN** [comment]
@hakale 试试`$D={(x_1, y_1) ,(x_2, y_2),\cdots, (x_m, y_m)}$`

**Comment by CHENXCHEN** [comment]
可以分享下你的这篇文章么,我很感兴趣.

**Comment by hakale** [comment]
@CHENXCHEN 这个解决了, 有一部分的`\dots` 改为`\cdots`也正常了.但是还是有一部分渲染不正确.
这些公式在Typora中都是能够正常解析的, 不是很明白在生成的时候为什么有些就是没有处理, 在写法上有什么要注意的么?比如{% math %}{% endmath %}这样?
如果是我的写法出的问题, 还请指教
这篇文章在[这里](http://hakale.cn/2017/10/11/machine-learning-notes/)
我把不能正确渲染的一部分抽到[这里](http://hakale.cn/2017/10/13/katex-test/)了

**Comment by hakale** [comment]
不好意思耽误了您的时间.
十分感谢您的项目
