### ISSUE TITLE
\textcolor{#ec4e8a}{}

### ISSUE THREAD

**Issue by swithun-liu** [CHENXCHEN/hexo-renderer-markdown-it-plus#30]
- I am using  [@upupming/hexo-renderer-markdown-it-plus](https://github.com/upupming/hexo-renderer-markdown-it-plus) for my hexo blog
- I can't  find the issue button in his forked repository, so I write an issue here
- I don't know if this extension caused this problem

![image](https://user-images.githubusercontent.com/42160297/78349791-b77b8c80-75d6-11ea-8763-974ef7525f19.png)

I used the Katax engine on vscode to write markdown,  and I can render `\textcolor{#...}{..}`.

but with hexo, the program will report an error

![image](https://user-images.githubusercontent.com/42160297/78349988-05909000-75d7-11ea-8e6c-0dc0eb74723c.png)

**Comment by MakerGYT** [comment]
You can try [markdown-it-latex2img](https://github.com/MakerGYT/markdown-it-latex2img)
```sh
$$
\textcolor{#ec4e8a}{sdf}
$$
```
![](https://math.now.sh/?from=%5Ctextcolor%7B%23ec4e8a%7D%7Bsdf%7D%0A)

**Comment by lancerXXXX** [comment]
Thanks, I will try
@MakerGYT
