### ISSUE TITLE
base64 Picture reference error

### ISSUE THREAD

**Issue by anlondon** [CHENXCHEN/hexo-renderer-markdown-it-plus#32]
Quote the picture of base64,
```
![xxx][image_name]
[image_name]:data:base.......
```
There is no problem in hexo-renderer-marked, but
hexo-renderer-markdown-it-plus will cause the image to be parsed incorrectly

**Comment by CHENXCHEN** [comment]
try like this is ok:
```markdown
![test image](data:image/png;base64,.......)
```
