### ISSUE TITLE
`breaks=false`时会渲染出多余空格。

### ISSUE THREAD

**Issue by yzlnew** [CHENXCHEN/hexo-renderer-markdown-it-plus#5]
其实和[这个](https://github.com/hexojs/hexo-renderer-markdown-it/issues/51)的问题一样。
md源文件用单个回车作为换行。

![2017-12-15 8 06 26](https://user-images.githubusercontent.com/4904877/34042150-3c9752b0-e1d6-11e7-864e-37e9f107415b.png)

**Comment by CHENXCHEN** [comment]
`markdown-it`中
如果设置 `breaks: false`，那么换行的定义操作将是：末尾两个空格或存在一行空行
如果设置 `breaks: true`，那么换行的定义操作是：单个回车作为换行
如果您希望使用单个回车作为换行，那么请将 `breaks` 设置为 `true`
> ps: 测试的时候请记得先 `hexo clean`

**Comment by yzlnew** [comment]
@CHENXCHEN 我应该描述再准确一点。
应该是从markdown->html的过程中，在`breaks: false`情况下，换行的定义没有问题，但是会渲染多一个空壳，如图所示“错”和“的”之间的被选中的黑色部分。

**Comment by CHENXCHEN** [comment]
可以给出一个 `markdown` 示例吗？

**Comment by CHENXCHEN** [comment]
如果设置 `breaks: false`
那么以下 `markdown` 是会渲染多一个空格
```markdown
错
开
```
会被渲染成
> 错 开

**Comment by yzlnew** [comment]
@CHENXCHEN 有没有办法可以避免这种情况，比较习惯类似 LaTeX 的写法，多行文字成一段。
现在用的 vim，比较笨拙的解决办法是 md 文件设置`fo-=t`，开启`set wrap`。
不过听到这不是个 bug 内心舒畅了许多。:smile:

**Comment by CHENXCHEN** [comment]
@yzlnew 抱歉忙到现在，您可以写个`markdown-it`插件将其默认的`breaks`实现覆盖掉，自定义成自己想要的操作
